config/routes.rb
Rails.application.routes.draw do
  resources :tweets, only: [:index, :create]
  root 'homes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body, presence: true
  validates :published, inclusion: [true, false]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @say = foo
  end

  private

  def foo
    'hello world'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
  end

  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to tweets_path
    else
      @tweets = Tweet.all
      render :index
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, :published)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/homes/index.html.haml
:sass
  .text-bold
    font-weight: bold

%p
  = @say.upcase

= link_to 'Tweets', tweets_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Demo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :published
    = f.check_box :published
  .actions
    = f.submit 'Save'

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', @tweet
\|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
%h1
  Listing tweets

%ul
  - @tweets.each do |tweet|
    %li
      = tweet.body
      = tweet.published


= form_with model: @tweet, local: true do |f|
  = f.text_field :body
  = f.check_box :published
  = f.submit 'SUBMIT'

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice

%p
  %b Body:
  = @tweet.body
%p
  %b Published:
  = @tweet.published

= link_to 'Edit', edit_tweet_path(@tweet)
\|
= link_to 'Back', tweets_path